id:
  id: "9031f588-0157-474c-b875-506c187242b7"
workflowId: "354e4ca6-e0e9-405a-b5c7-18af61370b78"
name: "Run ProtectionJob on Demand"
description: "Run Protection Job on Demand"
catalogRequestInfoHidden: true
forms:
- id: "d94873fc-8488-463c-9e9d-d324fa38c2e8"
  form:
    name: "Request form"
    designerLayout:
      pages:
      - id: "step0"
        label: "Run Protection Job On Demand"
        state:
          dependencies: []
          facets:
          - type: "visible"
            value:
              type: "constantClause"
              value:
                type: "boolean"
                value: true
        sections:
        - id: "__ASD_PRESENTATION_INSTANCE_SECTION"
          designerHidden: true
          state:
            dependencies: []
            facets:
            - type: "visible"
              value:
                type: "constantClause"
                value:
                  type: "boolean"
                  value: false
          rows:
          - items:
            - type: "field"
              size: 2
              id: "__ASD_PRESENTATION_INSTANCE"
              dataType:
                type: "primitive"
                typeId: "STRING"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
                - type: "derivedValue"
                  value:
                    type: "callback"
                - type: "visible"
                  value:
                    type: "constantClause"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 0
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
        - id: "step0_group0"
          label: "Select Endpoint"
          designerHidden: false
          state:
            dependencies: []
            facets:
            - type: "visible"
              value:
                type: "constantClause"
                value:
                  type: "boolean"
                  value: true
          rows:
          - items:
            - type: "field"
              size: 4
              id: "connection"
              label: "Cohesity Endpoint"
              description: "Cohesity Endpoint"
              dataType:
                type: "ref"
                componentTypeId: "com.vmware.csp.core.designer.service"
                classId: "CS:CohesityConnection"
                label: "CS:CohesityConnection"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
        - id: "step0_group1"
          label: "Select Cohesity Parameters"
          designerHidden: false
          state:
            dependencies: []
            facets:
            - type: "visible"
              value:
                type: "constantClause"
                value:
                  type: "boolean"
                  value: true
          rows:
          - items:
            - type: "field"
              size: 4
              id: "protectionJob"
              label: "Protection Job"
              description: "Protection Job"
              dataType:
                type: "ref"
                componentTypeId: "com.vmware.csp.core.designer.service"
                classId: "CS:ProtectionJob"
                label: "CS:ProtectionJob"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "runType"
              label: "Run Type (Specify the type of backup.)"
              description: "Run Type (Specify the type of backup.)"
              dataType:
                type: "primitive"
                typeId: "STRING"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
  scenario:
    usageClass: "SubmitUsage"
    id: "Request.Submit"
status: "PUBLISHED"
statusName: "Published"
version:
  version: "0.0.0"
  major: 0
  minor: 0
  micro: 0
component: true
componentConfiguration:
  scalable: false
  operations: []
builtIn: false
