id:
  id: "d4703e8f-577c-41a0-b795-1e31dae06f2a"
workflowId: "f26b91c7-8856-4682-ad16-00dbb7fe142d"
name: "Restore Virtual Machine"
description: "This is the workflow to restore virtual machine."
catalogRequestInfoHidden: true
forms:
- id: "b42b2028-3815-4d90-a260-6c12c1f2f452"
  form:
    name: "Request form"
    designerLayout:
      pages:
      - id: "step0"
        label: "Select Cohesity Endpoint and Backup Candidate"
        state:
          dependencies: []
          facets:
          - type: "visible"
            value:
              type: "constantClause"
              value:
                type: "boolean"
                value: true
        sections:
        - id: "__ASD_PRESENTATION_INSTANCE_SECTION"
          designerHidden: true
          state:
            dependencies: []
            facets:
            - type: "visible"
              value:
                type: "constantClause"
                value:
                  type: "boolean"
                  value: false
          rows:
          - items:
            - type: "field"
              size: 2
              id: "__ASD_PRESENTATION_INSTANCE"
              dataType:
                type: "primitive"
                typeId: "STRING"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
                - type: "derivedValue"
                  value:
                    type: "callback"
                - type: "visible"
                  value:
                    type: "constantClause"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 0
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
        - designerHidden: false
          state:
            dependencies: []
            facets: []
          rows:
          - items:
            - type: "field"
              size: 4
              id: "connection"
              label: "Cohesity Endpoint"
              description: "Cohesity Endpoint"
              dataType:
                type: "ref"
                componentTypeId: "com.vmware.csp.core.designer.service"
                classId: "CS:CohesityConnection"
                label: "CS:CohesityConnection"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "vmName"
              label: "Search Virtual Machine Name"
              description: "Search Virtual Machine Name"
              dataType:
                type: "primitive"
                typeId: "STRING"
              displayAdvice: "TEXTBOX"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "backupCandidates"
              label: "Backup Candidates"
              description: "Backup Candidates"
              dataType:
                type: "ref"
                componentTypeId: "com.vmware.csp.core.designer.service"
                classId: "CS:ObjectResource"
                label: "CS:ObjectResource"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
      - id: "step1"
        label: "Selection Restore Properties"
        state:
          dependencies: []
          facets:
          - type: "visible"
            value:
              type: "constantClause"
              value:
                type: "boolean"
                value: false
        sections:
        - designerHidden: false
          state:
            dependencies: []
            facets: []
          rows:
          - items:
            - type: "field"
              size: 4
              id: "protectionJobs"
              label: "Protection Job"
              description: "Protection Job"
              dataType:
                type: "ref"
                componentTypeId: "com.vmware.csp.core.designer.service"
                classId: "CS:ProtectionJobNameResource"
                label: "CS:ProtectionJobNameResource"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "snapshots"
              label: "Snapshots"
              description: "Snapshots"
              dataType:
                type: "primitive"
                typeId: "STRING"
              displayAdvice: "DROPDOWN"
              permissibleValues:
                type: "dynamic"
                customAllowed: false
                dependencies: []
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "machinePrefix"
              label: "Machine Prefix"
              description: "Machine Prefix"
              dataType:
                type: "primitive"
                typeId: "STRING"
              displayAdvice: "TEXTBOX"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "machineSuffix"
              label: "Machine Suffix"
              description: "Machine Suffix"
              dataType:
                type: "primitive"
                typeId: "STRING"
              displayAdvice: "TEXTBOX"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
          - items:
            - type: "field"
              size: 4
              id: "poweredOn"
              label: "Power On Machine"
              description: "Power On Machine"
              dataType:
                type: "primitive"
                typeId: "BOOLEAN"
              displayAdvice: "YES_NO"
              state:
                dependencies: []
                facets:
                - type: "editable"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: true
                - type: "refreshOnChange"
                  value:
                    type: "constant"
                    value:
                      type: "boolean"
                      value: false
              initialStaticState:
                dependencies: []
                facets: []
              labelDisplaySize: 2
              customField: false
              staticField: false
              refreshOnChange: false
              isMultiValued: false
              columns: []
              errors: []
  scenario:
    usageClass: "SubmitUsage"
    id: "Request.Submit"
status: "PUBLISHED"
statusName: "Published"
version:
  version: "1.0.0"
  major: 1
  minor: 0
  micro: 0
component: true
componentConfiguration:
  scalable: false
  operations: []
builtIn: false
